
package UniversityMS;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Pc
 */
public class ForgetPassword extends javax.swing.JFrame {

    /**
     * Creates new form ForgetPassword
     */
    Codes co = new Codes();
    String ans;

    public ForgetPassword() {
        initComponents();
           this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        // co.fillComboBox(AnsCom, "SELECT  Answer as jawab from users  ", "jawab");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtUser = new RSMaterialComponent.RSTextFieldMaterial();
        rSButtonMaterialIconTwo1 = new RSMaterialComponent.RSButtonMaterialIconTwo();
        rSButtonMaterialIconTwo2 = new RSMaterialComponent.RSButtonMaterialIconTwo();
        jLabel1 = new javax.swing.JLabel();
        pastxt = new RSMaterialComponent.RSTextFieldMaterial();
        qutxt = new RSMaterialComponent.RSTextFieldMaterial();
        rSButtonMaterialIconTwo3 = new RSMaterialComponent.RSButtonMaterialIconTwo();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        rSLabelImage1 = new necesario.RSLabelImage();
        txtans = new RSMaterialComponent.RSTextFieldMaterial();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtUser.setPlaceholder("Enter User Name:");
        jPanel1.add(txtUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 250, 31));

        rSButtonMaterialIconTwo1.setText("search");
        rSButtonMaterialIconTwo1.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.SEARCH);
        rSButtonMaterialIconTwo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMaterialIconTwo1ActionPerformed(evt);
            }
        });
        jPanel1.add(rSButtonMaterialIconTwo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 410, 120, 40));

        rSButtonMaterialIconTwo2.setText("I Remember My Password");
        rSButtonMaterialIconTwo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMaterialIconTwo2ActionPerformed(evt);
            }
        });
        jPanel1.add(rSButtonMaterialIconTwo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 480, 250, 40));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel1.setText("Password:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, -1, -1));

        pastxt.setEnabled(false);
        pastxt.setPlaceholder("Your Password");
        jPanel1.add(pastxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 360, -1, 30));

        qutxt.setEnabled(false);
        qutxt.setPlaceholder("QuestionsText");
        jPanel1.add(qutxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, -1, 30));

        rSButtonMaterialIconTwo3.setText("getPassword");
        rSButtonMaterialIconTwo3.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.GET_APP);
        rSButtonMaterialIconTwo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMaterialIconTwo3ActionPerformed(evt);
            }
        });
        jPanel1.add(rSButtonMaterialIconTwo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 410, 130, 40));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel2.setText("UserName:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel3.setText("S Question:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel4.setText("Answer:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, -1, -1));

        rSLabelImage1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Pc\\Desktop\\forget.png")); // NOI18N
        jPanel1.add(rSLabelImage1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 150, 150));

        txtans.setPlaceholder("Enter Answer");
        jPanel1.add(txtans, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 300, 250, 31));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rSButtonMaterialIconTwo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMaterialIconTwo2ActionPerformed
        // TODO add your handling code here:
        int option = JOptionPane.showConfirmDialog(null, "Are you sure you remember your password?", "Confirm", JOptionPane.YES_NO_OPTION);
        if (option == JOptionPane.YES_OPTION) {
            LogIn log = new LogIn();
            this.setVisible(false);
            log.setVisible(true);
        }

    }//GEN-LAST:event_rSButtonMaterialIconTwo2ActionPerformed

    private void rSButtonMaterialIconTwo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMaterialIconTwo1ActionPerformed
        // TODO add your handling code here:

        String username = txtUser.getText().trim();

        if (username.equals("")) {
            JOptionPane.showMessageDialog(null, "Please enter your username.");
            return;
        }

        co.search("SELECT secretQuestion FROM users WHERE user_name = '" + username + "'");

        try {
            if (co.rs.next()) {
                // Set the secret question
                qutxt.setText(co.rs.getString("secretQuestion"));
            } else {
                JOptionPane.showMessageDialog(null, "Username not found.");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }


    }//GEN-LAST:event_rSButtonMaterialIconTwo1ActionPerformed

    private void rSButtonMaterialIconTwo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMaterialIconTwo3ActionPerformed
        // TODO add your handling code here:
        String username = txtUser.getText().trim();
       String ans = txtans.getText().trim();
      //  String selectedAnswer = AnsCom.getSelectedItem().toString().trim();

        if (ans.equals("")) {
            JOptionPane.showMessageDialog(null, "Please enter answer.");
            return;
        }

        co.search("SELECT passwords, Answer FROM users WHERE user_name = '" + username + "'");

        try {
            if (co.rs.next()) {
                String correctAnswer = co.rs.getString("Answer").trim();

                if (ans.equalsIgnoreCase(correctAnswer)) {
                    // ✅ Show password if answer is correct
                    pastxt.setText(co.rs.getString("passwords"));

                    // ➕ Make password visible
                    //pastxt.setEchoChar((char) 0);  // Show the actual text
                    pastxt.setEditable(false);    // Make it read-only

                } else {
                    JOptionPane.showMessageDialog(null, "Incorrect answer.");
                }
            } else {
                JOptionPane.showMessageDialog(null, "User not found.");
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }

    }//GEN-LAST:event_rSButtonMaterialIconTwo3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ForgetPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ForgetPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ForgetPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ForgetPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ForgetPassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private RSMaterialComponent.RSTextFieldMaterial pastxt;
    private RSMaterialComponent.RSTextFieldMaterial qutxt;
    private RSMaterialComponent.RSButtonMaterialIconTwo rSButtonMaterialIconTwo1;
    private RSMaterialComponent.RSButtonMaterialIconTwo rSButtonMaterialIconTwo2;
    private RSMaterialComponent.RSButtonMaterialIconTwo rSButtonMaterialIconTwo3;
    private necesario.RSLabelImage rSLabelImage1;
    private RSMaterialComponent.RSTextFieldMaterial txtUser;
    private RSMaterialComponent.RSTextFieldMaterial txtans;
    // End of variables declaration//GEN-END:variables
}
