/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UniversityMS;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Pc
 */
public class LogIn extends javax.swing.JFrame {

    Codes co = new Codes();

    /**
     * Creates new form LogIn
     */
    public LogIn() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        rSButtonMaterialIconTwo1 = new RSMaterialComponent.RSButtonMaterialIconTwo();
        rSButtonMaterialIconTwo2 = new RSMaterialComponent.RSButtonMaterialIconTwo();
        txtuser = new RSMaterialComponent.RSTextFieldMaterial();
        pass = new RSMaterialComponent.RSPasswordMaterial();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        rSLabelImage1 = new rojerusan.RSLabelImage();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rSButtonMaterialIconTwo1.setText("LogIn");
        rSButtonMaterialIconTwo1.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.ARROW_UPWARD);
        rSButtonMaterialIconTwo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMaterialIconTwo1ActionPerformed(evt);
            }
        });
        jPanel2.add(rSButtonMaterialIconTwo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 290, 110, -1));

        rSButtonMaterialIconTwo2.setText("Forget");
        rSButtonMaterialIconTwo2.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.MEMORY);
        rSButtonMaterialIconTwo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMaterialIconTwo2ActionPerformed(evt);
            }
        });
        jPanel2.add(rSButtonMaterialIconTwo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, 110, -1));

        txtuser.setForeground(new java.awt.Color(0, 0, 0));
        txtuser.setPhColor(new java.awt.Color(0, 0, 0));
        txtuser.setPlaceholder("Enter your Username");
        jPanel2.add(txtuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 220, 30));

        pass.setForeground(new java.awt.Color(0, 0, 0));
        pass.setPhColor(new java.awt.Color(0, 0, 0));
        pass.setPlaceholder("Enter your Password");
        jPanel2.add(pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 220, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Pc\\Downloads\\padlock.png")); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, 60));

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\Pc\\Downloads\\user (1).png")); // NOI18N
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, 60));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 0, 360, 410));

        jPanel3.setBackground(new java.awt.Color(0, 0, 204));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tw Cen MT", 0, 30)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("University Management System");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 380, 50));

        rSLabelImage1.setIcon(new javax.swing.ImageIcon("D:\\From Downloads\\A new twist on educational testing.jpg")); // NOI18N
        jPanel3.add(rSLabelImage1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 390, 360));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rSButtonMaterialIconTwo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMaterialIconTwo1ActionPerformed
        // TODO add your handling code here:
        String sql = "select user_name, passwords,r.user_role_no from users u, staff s, user_role r where u.st_no = s.st_no and r.user_role_no = u.user_role_no and user_name = '" + txtuser.getText() + "' and passwords = '" + pass.getText() + "'";
        co.search(sql);
        try {
            if (co.rs.next()) {
                int role = Integer.parseInt(co.rs.getString("r.user_role_no"));
                if (role == 2) {                    
                    this.hide();
                    Dashboard dash = new Dashboard();
                    dash.lp3.setVisible(false);
                    dash.lp6.setVisible(false);
                    dash.show();
                    
                }
             
                else {
                    this.hide();
                    Dashboard dash = new Dashboard();
                    dash.show();
                }
            } else {
                JOptionPane.showMessageDialog(null, "UserName or password invalid");
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }

    }//GEN-LAST:event_rSButtonMaterialIconTwo1ActionPerformed

    private void rSButtonMaterialIconTwo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMaterialIconTwo2ActionPerformed
        // TODO add your handling code here:
        ForgetPassword fp = new ForgetPassword(); 
        this.setVisible(false);
        fp.setVisible(true);
       
    }//GEN-LAST:event_rSButtonMaterialIconTwo2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LogIn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private RSMaterialComponent.RSPasswordMaterial pass;
    private RSMaterialComponent.RSButtonMaterialIconTwo rSButtonMaterialIconTwo1;
    private RSMaterialComponent.RSButtonMaterialIconTwo rSButtonMaterialIconTwo2;
    private rojerusan.RSLabelImage rSLabelImage1;
    private RSMaterialComponent.RSTextFieldMaterial txtuser;
    // End of variables declaration//GEN-END:variables
}
