/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UniversityMS;

import java.sql.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Pc
 */
public class TransferAccounts extends javax.swing.JFrame {

   Codes co = new Codes();
   String id, to, from;
    public TransferAccounts() {
        initComponents();
        co.fillComboBox(com1, "SELECT concat(ac1.acc_no, ',', ac1.institution) from_acc from account ac1 ", "from_acc");
       co.fillComboBox(com2, "SELECT concat(ac2.acc_no, ',', ac2.institution) to_acc from account ac2 ", "to_acc");
       this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
       this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        com2 = new RSMaterialComponent.RSComboBoxMaterial();
        com1 = new RSMaterialComponent.RSComboBoxMaterial();
        destxt = new RSMaterialComponent.RSTextFieldMaterial();
        date = new com.toedter.calendar.JDateChooser();
        txtamount = new RSMaterialComponent.RSTextFieldMaterial();
        rSButtonMaterialIconOne5 = new RSMaterialComponent.RSButtonMaterialIconOne();
        rSButtonMaterialIconOne3 = new RSMaterialComponent.RSButtonMaterialIconOne();
        rSButtonMaterialIconOne4 = new RSMaterialComponent.RSButtonMaterialIconOne();
        rSButtonMaterialIconOne1 = new RSMaterialComponent.RSButtonMaterialIconOne();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtser = new RSMaterialComponent.RSTextFieldMaterial();
        rSButtonIconTwo1 = new RSMaterialComponent.RSButtonIconTwo();

        jLabel3.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel3.setText("From Acc:");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(37, 45, 223));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Transfer Accounts", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 30), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -4, 460, 60));

        jPanel2.setBackground(new java.awt.Color(102, 255, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        com2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "------Select to Acc------" }));
        com2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                com2ActionPerformed(evt);
            }
        });
        jPanel2.add(com2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, 220, 30));

        com1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "------Select From Acc------" }));
        com1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                com1ActionPerformed(evt);
            }
        });
        jPanel2.add(com1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 220, 30));

        destxt.setPhColor(new java.awt.Color(0, 0, 0));
        destxt.setPlaceholder("Description");
        jPanel2.add(destxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 320, 220, 30));
        jPanel2.add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, 220, 30));

        txtamount.setForeground(new java.awt.Color(0, 0, 0));
        txtamount.setPhColor(new java.awt.Color(0, 0, 0));
        txtamount.setPlaceholder("Amount");
        jPanel2.add(txtamount, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, 220, 30));

        rSButtonMaterialIconOne5.setBackground(new java.awt.Color(102, 255, 102));
        rSButtonMaterialIconOne5.setText("Save");
        rSButtonMaterialIconOne5.setBackgroundHover(new java.awt.Color(37, 45, 223));
        rSButtonMaterialIconOne5.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.SAVE);
        rSButtonMaterialIconOne5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMaterialIconOne5ActionPerformed(evt);
            }
        });
        jPanel2.add(rSButtonMaterialIconOne5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 80, -1));

        rSButtonMaterialIconOne3.setBackground(new java.awt.Color(102, 255, 102));
        rSButtonMaterialIconOne3.setText("Update");
        rSButtonMaterialIconOne3.setBackgroundHover(new java.awt.Color(37, 45, 223));
        rSButtonMaterialIconOne3.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.UPDATE);
        rSButtonMaterialIconOne3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMaterialIconOne3ActionPerformed(evt);
            }
        });
        jPanel2.add(rSButtonMaterialIconOne3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 380, 90, -1));

        rSButtonMaterialIconOne4.setBackground(new java.awt.Color(102, 255, 102));
        rSButtonMaterialIconOne4.setText("Delete");
        rSButtonMaterialIconOne4.setBackgroundHover(new java.awt.Color(37, 45, 223));
        rSButtonMaterialIconOne4.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.DELETE);
        rSButtonMaterialIconOne4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMaterialIconOne4ActionPerformed(evt);
            }
        });
        jPanel2.add(rSButtonMaterialIconOne4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 380, 90, -1));

        rSButtonMaterialIconOne1.setBackground(new java.awt.Color(102, 255, 102));
        rSButtonMaterialIconOne1.setText("Clear");
        rSButtonMaterialIconOne1.setBackgroundHover(new java.awt.Color(37, 45, 223));
        rSButtonMaterialIconOne1.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.CLEAR);
        jPanel2.add(rSButtonMaterialIconOne1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 380, 80, -1));

        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel1.setText("Description:");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel2.setText("From Acc:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel4.setText("To Acc:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel5.setText("Amount:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel6.setText("Date:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, -1, -1));

        txtser.setForeground(new java.awt.Color(0, 0, 0));
        txtser.setPlaceholder("Search");
        jPanel2.add(txtser, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, 190, 30));

        rSButtonIconTwo1.setBackground(new java.awt.Color(102, 255, 102));
        rSButtonIconTwo1.setBackgroundHover(new java.awt.Color(37, 45, 223));
        rSButtonIconTwo1.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.SEARCH);
        rSButtonIconTwo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonIconTwo1ActionPerformed(evt);
            }
        });
        jPanel2.add(rSButtonIconTwo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 460, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rSButtonMaterialIconOne5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMaterialIconOne5ActionPerformed
        String oper = "insert";
        Date d1 = new Date(date.getDate().getTime());
        String sql = "call transfer_accounts_pro('"+from+"', '"+to+"', '"+txtamount.getText()+"', '"+d1+"', '"+destxt.getText()+"', '"+oper+"' ,null)";
        co.setSql(sql);
    }//GEN-LAST:event_rSButtonMaterialIconOne5ActionPerformed

    private void rSButtonMaterialIconOne3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMaterialIconOne3ActionPerformed
    String oper = "update";
        Date d1 = new Date(date.getDate().getTime());
        String sql = "call transfer_accounts_pro('"+from+"', '"+to+"', '"+txtamount.getText()+"', '"+d1+"', '"+destxt.getText()+"',  '"+oper+"' ,'"+id+"')";
        co.setSql(sql);      
    }//GEN-LAST:event_rSButtonMaterialIconOne3ActionPerformed

    private void rSButtonMaterialIconOne4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMaterialIconOne4ActionPerformed
                if(JOptionPane.showConfirmDialog(null, "Ma hubtaa")==JOptionPane.YES_OPTION){
                    String oper = "delete";
        Date d1 = new Date(date.getDate().getTime());
        String sql = "call transfer_accounts_pro('"+from+"', '"+to+"', '"+txtamount.getText()+"', '"+d1+"', '"+destxt.getText()+"',  '"+oper+"' ,'"+id+"')";
        co.setSql(sql); 
                }
    }//GEN-LAST:event_rSButtonMaterialIconOne4ActionPerformed

    private void rSButtonIconTwo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonIconTwo1ActionPerformed
    co.search("SELECT t_no, concat(ac1.acc_no, ',', ac1.institution) from_acc, concat(ac2.acc_no, ',', ac2.institution) to_acc, amount, tr_date, description from account ac1, account ac2, transfer_accounts t where  ac1.acc_no = t.from_acc and ac2.acc_no = t.to_acc and ac1.acc_no <> ac2.acc_no and t.t_no='"+txtser.getText()+"' ");
    try{
        if(co.rs.next()){
                id = co.rs.getString("t_no");
               
                com1.setSelectedItem(co.rs.getString("from_acc"));
                com2.setSelectedItem(co.rs.getString("to_acc"));
                txtamount.setText(co.rs.getString("amount"));
                date.setDate(co.rs.getDate("tr_date"));
               destxt.setText(co.rs.getString("description"));

            }
      else{
                JOptionPane.showMessageDialog(null, txtser.getText()+" not found");
            }
    }catch(Exception e){
                    JOptionPane.showMessageDialog(null, e.getMessage());

    }
    }//GEN-LAST:event_rSButtonIconTwo1ActionPerformed

    private void com1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_com1ActionPerformed
        // TODO add your handling code here:
        String array1[] = com1.getSelectedItem().toString().split(",");
        from = array1[0];
    }//GEN-LAST:event_com1ActionPerformed

    private void com2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_com2ActionPerformed
        // TODO add your handling code here:
         String array1[] = com2.getSelectedItem().toString().split(",");
        to = array1[0];
    }//GEN-LAST:event_com2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TransferAccounts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TransferAccounts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TransferAccounts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TransferAccounts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TransferAccounts().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private RSMaterialComponent.RSComboBoxMaterial com1;
    private RSMaterialComponent.RSComboBoxMaterial com2;
    private com.toedter.calendar.JDateChooser date;
    private RSMaterialComponent.RSTextFieldMaterial destxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private RSMaterialComponent.RSButtonIconTwo rSButtonIconTwo1;
    private RSMaterialComponent.RSButtonMaterialIconOne rSButtonMaterialIconOne1;
    private RSMaterialComponent.RSButtonMaterialIconOne rSButtonMaterialIconOne3;
    private RSMaterialComponent.RSButtonMaterialIconOne rSButtonMaterialIconOne4;
    private RSMaterialComponent.RSButtonMaterialIconOne rSButtonMaterialIconOne5;
    private RSMaterialComponent.RSTextFieldMaterial txtamount;
    private RSMaterialComponent.RSTextFieldMaterial txtser;
    // End of variables declaration//GEN-END:variables
}
